[package]
name = "disk_monitor"
version = "0.1.0"
authors = ["kory.zhang <kory.zhang@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
